Feat: добавить reviews
tectupobllluk/java-filmorate pull request #10
Opened 2023-10-26 00:40 UTC by CharlesMickey

2023-10-26 06:05 UTC, CharlesMickey commented
![image](https://github.com/tectupobllluk/java-filmorate/assets/50279935/baea1e90-988e-4574-a22d-975ccf1a9d4b)

2023-10-30 11:48 UTC, FantasticNone approved these changes

2023-10-30 16:54 UTC, Pavel-Vinogradov reviewed
Чекнул

2023-10-30 21:59 UTC, tectupobllluk requested changes
Нужно поправить некоторые моментики

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    ReviewService reviewService;
Поле лучше сделать private final

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    }
Лучше сделать через аннотацию @RequiredArgsConstructor

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @Size(min = 1, max = 500)
не увидел в задании и тестах ограничения по размеру контента

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Long userId;
Можно использовать @Positive для валидации userId > 0

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Long filmId;
тоже, что и с userId

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/resources/schema.sql
> +    content_review VARCHAR(200) NOT NULL,
откуда ограничение в 200?

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewLikesController.java
> +    }
лучше сделать аннотацией

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewLikesRepository.java
> +    }
лучше сделать аннотацией

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewLikesRepository.java
> +        // Проверяем, существует ли запись с заданными reviewId и userId
комменты мой ревьюер не любит

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewRepository.java
> +@Primary
зачем primary?

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewRepository.java
> +    }
то же что и везде, сделай через аннотацию

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewRepository.java
> +
; в конце всех sql запросов + лишняя строка тут

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseReviewLikeService.java
> +    UserRepository userRepository;
private final

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseReviewLikeService.java
> +    }
через аннотацию

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseReviewService.java
> +    UserRepository userRepository;
private final

2023-10-30 21:59 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseReviewService.java
> +    }
через аннотацию

2023-10-30 22:40 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    }
В ревью, и не только, если пишешь, что нечто лучше иного - пиши почему)

2023-10-30 22:40 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @Size(min = 1, max = 500)
В свою очередь не видел запрета на ограничения

2023-10-30 22:41 UTC, CharlesMickey commented on src/main/resources/schema.sql
> +    content_review VARCHAR(200) NOT NULL,
Конечно этику общения нужно подтягивать.

2023-10-30 22:46 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewLikesController.java
> +    }
Опять лучше) 
Лучше почему?

Я опираюсь на теорию 
![image](https://github.com/tectupobllluk/java-filmorate/assets/50279935/7c0b14bd-e951-42f5-ad1e-efbc9a110434)

2023-10-30 22:49 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewRepository.java
> +
Почему лишняя?

2023-10-30 22:50 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    }
ну, как минимум, чтобы сохранить одинаковый стиль написания кода в проекте, а также ты заменяешь 3-4 строчки одной...

2023-10-30 22:50 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @Size(min = 1, max = 500)
по тз не было

2023-10-30 22:51 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewLikesRepository.java
> +        // Проверяем, существует ли запись с заданными reviewId и userId
Это его личные предпочтения. 
Их наличие ничего не нарушает)

2023-10-30 22:54 UTC, tectupobllluk commented on src/main/resources/schema.sql
> +    content_review VARCHAR(200) NOT NULL,
Чем тебе вопрос не понравился? Это не наезд, а именно вопрос, потому что видел такие ограничения и не раз, может я что-то не знаю, вот и спрашиваю...

2023-10-30 22:54 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewRepository.java
> +@Primary
Копипаста)

2023-10-30 22:55 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewLikesController.java
> +    }
Выше написал

2023-10-30 22:57 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewLikesRepository.java
> +        // Проверяем, существует ли запись с заданными reviewId и userId
Конечно не нарушает, но он скажет убрать, я лишь заранее об этом говорю...

2023-10-30 22:58 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewRepository.java
> +
Там две строки перед return, неправильно выделил видимо

2023-10-30 23:14 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewLikesController.java
> +    }
Не. Я привел конкретный пример, на который опираюсь.
Кроме стиля, лучше то чем?)

2023-10-30 23:27 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbReviewLikesRepository.java
> +        // Проверяем, существует ли запись с заданными reviewId и userId
Мы ж в свободном обществе живем. 
Командой решим оставлять комменты и на каждый метод напишем)

2023-10-30 23:45 UTC, CharlesMickey commented on src/main/resources/schema.sql
> +    content_review VARCHAR(200) NOT NULL,
Угораю, соррян. Не принимай близко) 
Все четки написал везде

2023-10-31 05:37 UTC, tectupobllluk approved these changes

2023-10-31 06:31 UTC, Pavel-Vinogradov approved these changes

2023-10-31 07:07 UTC, merged