Add common films
tectupobllluk/java-filmorate pull request #12
Opened 2023-10-27 09:58 UTC by FantasticNone

2023-10-30 09:30 UTC, CharlesMickey approved these changes
Если что то и можно улучшить радикально, узнаем мы это после ревью настоящего ревьюера)

2023-10-30 09:30 UTC, CharlesMickey commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseFilmService.java
> +    }*/
Как говорит мой ревьюер - не оставляй законченный код).

2023-10-31 06:51 UTC, tectupobllluk requested changes
Все топ, осталось только дождаться моего мерджа режиссёров и поправить комментную часть)

2023-10-31 06:51 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseFilmService.java
> +        List<Director> directors = filmDirectorRepository.getDirectorsIdByFilmId(film.getId())
Я сделал отдельный метод погрузки режиссеров к фильму, так что тут тебе проще)
И разве тут не нужна подгрузка жанров?

2023-11-01 10:34 UTC, tectupobllluk requested changes
Нужно немного подправить

2023-11-01 10:34 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseFilmService.java
> +        for (Film film : films) {
Слушай, наверное я тебя обманул, тут не нужна подгрузка ничего, я же ее в FilmRowMapper делаю, когда объект создаю... То есть возвращай сразу в return результат вызова метода репозитория.

2023-11-01 10:34 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Лишняя строка

2023-11-01 10:46 UTC, FantasticNone commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
почему? эту строку использует контроллер

2023-11-01 11:08 UTC, tectupobllluk approved these changes
Топ!

2023-11-01 11:35 UTC, merged