add-feed
tectupobllluk/java-filmorate pull request #14
Opened 2023-10-30 19:22 UTC by Pavel-Vinogradov

Автотесты не прошли , требуется ветка add-reviews

как все  готова готов нагрузить

2023-10-31 07:49 UTC, CharlesMickey approved these changes

2023-11-02 21:53 UTC, tectupobllluk requested changes
Нужно вносить правки!

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +public class FeedController {
непонятно зачем ты создал отдельный контроллер на это, тут даже по пути понятно, что этот метод должен находиться в UserController

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> -    }
зачем ты удаляешь метод, он нужен

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbFeedRepository.java
> +
лишний перенос строки

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbFeedRepository.java
> +@Component
тут не component, а @Repository

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/EventDbStorage.java
> +
лишний перенос

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseUserService.java
> -
зачем удалил, все методы нужны, не нужно трогать уже отлаженный код, это относится ко всему проекту в целом, добавления допускаются, код стайл чужого нет

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> -    void deleteUser(long userId);
написал выше

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/resources/data.sql
> +-- Вставка данных в таблицу типов операций
комменты все убери, у меня ревьюер это не любит

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/resources/data.sql
> +MERGE INTO event_types (type_id, type_name)
тут лучше input использовать, тк БД очищаются

2023-11-02 21:53 UTC, tectupobllluk commented on src/main/resources/schema.sql
> -    film_directors;
не надо трогать чужой код

2023-11-04 08:09 UTC, tectupobllluk approved these changes

2023-11-04 21:45 UTC, merged