Add recommendations
tectupobllluk/java-filmorate pull request #20
Opened 2023-11-01 20:11 UTC by Pavel-Vinogradov

Add recommendations

2023-11-02 00:08 UTC, tectupobllluk requested changes
Нужны некоторые правки

2023-11-02 00:08 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbFilmRepository.java
> +                "WHERE user_id = ?))";
Попробуй сделать запрос:
"SELECT sl.user_id " +
"FROM likes AS l " +
"LEFT JOIN likes AS sl ON l.film_id = sl.film_id " +
"WHERE l.user_id = ? " +
"AND l.user_id <> sl.user_id " +
"GROUP BY l.user_id " +
"ORDER BY COUNT(l.user_id) DESC " +
"LIMIT 1;" - первый запрос к БД, который вернет id пользователя с наибольшим совпадением по лайкам (вместо ? - параметр userId)

"SELECT f.* " +
"FROM films AS f " +
"RIGHT JOIN likes AS l " +
"WHERE l.user_id = ? " +
"AND f.film_id NOT IN(" +
"SELECT fu.film_id " +
"FROM films AS fu " +
"RIGHT JOIN likes AS lu ON fu.film_id = lu.film_id " +
"WHERE lu.user_id = ?);" - второй запрос к БД, где возвращается список нужных фильмов (первый ? - результат первого запроса к БД; второй ? - userId)
Вот как у меня получилось, вроде лаконичнее выглядит и читаемее...

2023-11-02 00:08 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbFilmRepository.java
> +
лишняя пустая строка

2023-11-02 00:08 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseUserService.java
> +        User user =  this.getUser(userId);
this не нужен, можно просто вызвать метод

2023-11-02 00:08 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/service/BaseUserService.java
> +
лишняя пустая строчка

2023-11-02 21:35 UTC, Pavel-Vinogradov commented on src/main/java/ru/yandex/practicum/filmorate/repository/DbFilmRepository.java
> +                "WHERE user_id = ?))";
SQL запрос не прошел 
пробовал через функцию описать 
public List<Film> getRecommendedFilms(long userId) {
    final String sqlQuery = 
        "WITH UserLikes AS (" +
        "    SELECT user_id, COUNT(DISTINCT film_id) AS matches " +
        "    FROM likes " +
        "    WHERE user_id <> ? AND film_id IN (SELECT film_id FROM likes WHERE user_id = ?) " +
        "    GROUP BY user_id " +
        "), " +
        "MaxMatches AS (" +
        "    SELECT MAX(matches) AS max_matches " +
        "    FROM UserLikes " +
        "), " +
        "TopUsers AS (" +
        "    SELECT user_id " +
        "    FROM UserLikes " +
        "    WHERE matches = (SELECT max_matches FROM MaxMatches) " +
        ") " +
        "SELECT f.*, m.* " +
        "FROM films AS f " +
        "JOIN mpa AS m ON m.mpa_id = f.mpa_id " +
        "WHERE f.film_id IN ( " +
        "    SELECT DISTINCT film_id " +
        "    FROM likes " +
        "    WHERE user_id IN (SELECT user_id FROM TopUsers) " +
        "    AND f.film_id NOT IN (SELECT film_id FROM likes WHERE user_id = ?) " +
        ")";

    return jdbcTemplate.query(sqlQuery, new FilmRowMapper(), userId, userId, userId);
}
все равно не проходит, времени сейчас нет толком писать SQL запрос. 
если будет  время то вот sql запрос 
WITH UserLikes AS (
    SELECT user_id, COUNT(DISTINCT film_id) AS matches
    FROM likes
    WHERE user_id <> ? AND film_id IN (SELECT film_id FROM likes WHERE user_id = ?)
    GROUP BY user_id
),
MaxMatches AS (
    SELECT MAX(matches) AS max_matches
    FROM UserLikes
),
TopUsers AS (
    SELECT user_id
    FROM UserLikes
    WHERE matches = (SELECT max_matches FROM MaxMatches)
)
SELECT f.*, m.*
FROM films AS f
JOIN mpa AS m ON m.mpa_id = f.mpa_id
WHERE f.film_id IN (
    SELECT DISTINCT film_id
    FROM likes
    WHERE user_id IN (SELECT user_id FROM TopUsers)
    AND f.film_id NOT IN (SELECT film_id FROM likes WHERE user_id = ?)
);
не проходит 2 теста

2023-11-02 22:37 UTC, tectupobllluk approved these changes

2023-11-03 06:05 UTC, CharlesMickey approved these changes

2023-11-03 23:25 UTC, merged