Feat: добавить удаление User и Film
tectupobllluk/java-filmorate pull request #7
Opened 2023-10-25 09:37 UTC by CharlesMickey

2023-10-25 19:43 UTC, tectupobllluk requested changes
Хорошая работа! Небольшая ошибочка в названии метода UserController

2023-10-25 19:43 UTC, tectupobllluk commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void deleteFilm(@PathVariable long id) {
Ошибка в названии метода для удаления пользователей

2023-10-26 05:37 UTC, tectupobllluk approved these changes

2023-10-26 07:16 UTC, FantasticNone approved these changes

2023-10-30 23:38 UTC, merged